### ISSUE TITLE
Replace all code blocks with fenced code

### ISSUE THREAD

**Issue by holzkohlengrill** [TeamFlowerPower/kb#2]
Replace all code blocks like `    ::python3` with fenced code:

```
    ```python3
    # code
    ```
```

Github only supports the latter.

**Comment by stg7** [comment]
should be solved in latest commits, e.g. 526d05d5988684ee1ffcaabc4e88d2d877aca72a , i'm a bit annoyed of the fact that 
(1) with the wiki function u cannot see the same history in the webpage
(2) also it seems that issues are not handled in commit messages in the wiki, that is the case in a pure repo

@holzkohlengrill  check if it fits now, then the issue can be closed
