### ISSUE TITLE
moving from wiki to real repo

### ISSUE THREAD

**Issue by stg7** [TeamFlowerPower/kb#3]
as i already mentioned in the #2  maybe we should consider moving the wiki to the real repo, 
then the starting "README.md" could be just the sidebar of the wiki.

what do you thing about this @holzkohlengrill

**Comment by holzkohlengrill** [comment]
We would not have any *permanent* sidebar in this case which is in my opinion important (mainly usability and convenience reasons).

Another option would be using a plain repo in combination with a github pages supported framework like Jekyll. That's for sure a matter of taste to use it or not.

**Comment by holzkohlengrill** [comment]
Closed; Currently no *ideal* solution.
